// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKH1wG5WZ2P9beG910P54CwmTChHUM3SI',
    appId: '1:232579008857:web:3323ee2b1b3e28b3876448',
    messagingSenderId: '232579008857',
    projectId: 'prova2-17e12',
    authDomain: 'prova2-17e12.firebaseapp.com',
    storageBucket: 'prova2-17e12.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb09vu5BY72rpBQgnv5OFI53xdq4ptfTg',
    appId: '1:232579008857:android:00969c3ae5e788c5876448',
    messagingSenderId: '232579008857',
    projectId: 'prova2-17e12',
    storageBucket: 'prova2-17e12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFz5BnyqppR0WA7PXTZNX5vIYb-DCJ6JA',
    appId: '1:232579008857:ios:6842d7f4f18e3b89876448',
    messagingSenderId: '232579008857',
    projectId: 'prova2-17e12',
    storageBucket: 'prova2-17e12.firebasestorage.app',
    iosBundleId: 'com.example.provaConnectFirebase',
  );
}
